[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Amy Keibler <amy@genomoncology.com>"]
edition = "2018"

[[bin]]
name = "day-one"

[[bin]]
name = "day-two"

[[bin]]
name = "day-three"

[[bin]]
name = "day-four"

[dependencies]
nom = "5.0.1"
